---



#1.INSTALL GITLAB
- name: INSTALL  GITLAB
  sudo: yes
  hosts: 
   - GITLAB
  remote_user: root
  gather_facts: True
  roles:
    - GITLAB
  tags:
   - GITLAB

#2.INSTALL JENKINS
- name: INSTALL JENKINS
  sudo: yes
  hosts:
   - JENKINS
  remote_user: root
  gather_facts: False
  roles:
    - JENKINS
  tags:
   - JENKINS
#3.INSTALL ANSIBLE
- name: INSTALL ANSIBLE
  sudo: yes
  hosts:
   - ANSIBLE
  remote_user: root
  gather_facts: False
  roles:
    - ANSIBLE
  tags:
   - ANSIBLE

#4.INSTALL SONARQUBE
- name: INSTALL SONARQUBE
  sudo: yes
  hosts:
   - SONARQUBE
  remote_user: root
  gather_facts: True
  roles:
    - SONARQUBE
  tags:
   - SONARQUBE




#5.INSTALL SELENIUM
- name: INSTALL SELENIUM
  sudo: yes
  hosts:
   - SELENIUM
  remote_user: zeusadmin
  gather_facts: True
  roles:
    - SELENIUM
  tags:
   - SELENIUM























